### ISSUE TITLE
[Feature] Page-icon: support custom icons (local and by url)

### ISSUE THREAD

**Issue by dmytrodubinin** [yoyurec/logseq-banners-plugin#17]
Thank you very much for a great plugin!
It would be nice to add the ability to add your icons not only as emoji, but also via a link (as it is done in the banner). Ideally support local address or external link

**Comment by yoyurec** [comment]
Is not so easy as it sounds ))

**Comment by yoyurec** [comment]
Will enable custom icons (Nerd font) with instructions . Soon...

**Comment by yoyurec** [comment]
BTW, icons rendered via CSS `content` propperty. So you can insert `dataURI` instead of emoji icon: `url(".....data URI here.....")`

![image](https://user-images.githubusercontent.com/137919/191315507-97931cd9-0a09-4581-b635-f5e1d902b558.png)

**Comment by colinbate** [comment]
While `content` does allow for a `url()` value, your code is adding quotes around the value from the page property, so this option doesn't work, as it is treated like a string.
