### ISSUE TITLE
[Feture request] Cache the random image until next re-index

### ISSUE THREAD

**Issue by SainoNamkho** [yoyurec/logseq-banners-plugin#35]
Is it able to keep the random image unchanged each time when logseq is opened?
Maybe writing a `cached-banner` property entry for the actual image url?

**Comment by yoyurec** [comment]
It's random image )) It requested every page reload. If it will be cached it will not be random anymore....

**Comment by yoyurec** [comment]
Second question - how to know that image is random? It's just URL field (which can be any), provided by user, not internal `random` functionality.

**Comment by SainoNamkho** [comment]
> It's random image )) It requested every page reload. If it will be cached it will not be random anymore....

Emmm, I don't know if the plugin has file system access to cache a picture.

And what I mentioned is "random" as per "pages", though seems unrealizable ....

> Second question - how to know that image is random? It's just URL field (which can be any), provided by user, not internal `random` functionality.

I'm not very sure, but does something like this help?
```js
> await fetch('https://source.unsplash.com/featured/1600x900').then(res => res.url)
https://images.unsplash.com/photo-1655933146545-e9792337d34e?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=900&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY1ODAyNjQ3NQ&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1600
```
