### ISSUE TITLE
Feature request Toggle via Properties to turn-off banner

### ISSUE THREAD

**Issue by cliffordx** [yoyurec/logseq-banners-plugin#37]
Can we have an option to toggle on/off the banner in cases when we don't want to have a banner displayed? Use case when you want to have a presentation and you don't need to show the banner, instead a clean block of text and some image in the block. Thanks!

**Comment by yoyurec** [comment]
will add, just thought about it few days ago....

**Comment by cliffordx** [comment]
Great, thanks!

**Comment by yoyurec** [comment]
Done!
Check latest **v2.1.0**
Set `banner:: false` in page props to disable banner.
