### ISSUE TITLE
Left and right side bar turned off the banner width extends

### ISSUE THREAD

**Issue by cliffordx** [yoyurec/logseq-banners-plugin#38]
For the latest update (2.0) the banner extends to left and right when the both sidebars turn off. 

On another note, I cannot upload a screenshot.

**Comment by yoyurec** [comment]
just copy-paspe screnn or drag-n-drop

**Comment by yoyurec** [comment]
wasn't is extended before? are u sure?
https://raw.githubusercontent.com/yoyurec/logseq-banners-plugin/f2255704e280354863dfcef05efdce58da140913/Screenshot%202022-06-27%20at%2010.46.44%20PM.png

**Comment by yoyurec** [comment]
if you mean "extends" = "not like in plugin screenshots" - the Solarized Extended theme used

**Comment by cliffordx** [comment]
<img width="1785" alt="Screen Shot 2022-07-28 at 7 03 56 PM" src="https://user-images.githubusercontent.com/7141739/181490710-358efcc3-fd88-4c93-8af5-35a2f28cba4f.png">

Yes, I think it has to do with the theme I use.

**Comment by yoyurec** [comment]
what version of SolExt? as i see on screens - not latest.
BTW, where have you found info about new vesrrsion of Banners?

**Comment by cliffordx** [comment]
> what version of SolExt? as i see on screens - not latest.
> BTW, where have you found info about new vesrrsion of Banners?

I click the  "Check Update"  and it shows there's new update. Yes, I have old version.

I will update it now.
<img width="406" alt="Screen Shot 2022-07-28 at 7 25 27 PM" src="https://user-images.githubusercontent.com/7141739/181494333-21ee6aa3-a5d9-4a6e-b5cd-b14689259172.png">

**Comment by cliffordx** [comment]
I can confirm it is now working. Thank you for this nice plugin and your  SolExt Theme.

**Comment by yoyurec** [comment]
for updates info you can check here - https://discord.com/channels/725182569297215569/896368413243494430
