### ISSUE TITLE
Where is "Always render" in setting?

### ISSUE THREAD

**Issue by bwnjnOEI** [yoyurec/logseq-banners-plugin#39]
The calendar widget doesn't appear only for weather, am I missing something, I don't find this option in the settings? Also, can I even customize other widgets based on indify.co?

**Comment by yoyurec** [comment]
did you read instructions in redme?
did you installed Block calendar plugin (settings to always render in it, the last one)?

you can add any iframes, any widgets - there is a field for it. now 2 iframes, you can add yours. but customize size/position via custom.css

**Comment by bwnjnOEI** [comment]
Sorry for the skipped reading that made me miss important information 😂
