### ISSUE TITLE
[[Feature request]] disable banners by default

### ISSUE THREAD

**Issue by farconada** [yoyurec/logseq-banners-plugin#40]
I want to use banners only in selected pages but I dont want banners by default.
Banners could help to remember pages with image associations.
Is it possible to have a flag in settings to disable banners by default?

Thanks

**Comment by yoyurec** [comment]
just delete URL from filed )
![image](https://user-images.githubusercontent.com/137919/182020424-ac66b771-c43c-4d46-a6e8-78c4160fff42.png)

**Comment by farconada** [comment]
thanks, for your answer
