### ISSUE TITLE
[Feature Request] Get random Quote

### ISSUE THREAD

**Issue by emms007** [yoyurec/logseq-banners-plugin#41]
Thanks a lot for this plugin.
I store many "quote" under the #quote tag. Would it be possible to display in the journal banner a random quote? I already use other plugins for that through the journal entries (https://github.com/QWxleA/logseq-interstitial-heading-plugin => /quote), but having it mashed-up automatically in the beautiful header would be even more beautiful.

**Comment by emms007** [comment]
My quotes are for most of them stored in very simple format : 
- this is a #Quote

**Comment by yoyurec** [comment]
have no idea how to fit it.... all area filled with widgets )
or you not using them?

**Comment by emms007** [comment]
I am not using the agenda - somehow it was not in the default set and I don't really need it neither.
I can easily project a quote one a full screen view or half-full-screen, see below. 

![image](https://user-images.githubusercontent.com/171033/182549647-a79a242a-f6b5-4be0-993d-14d8dd5c9469.png)
![image](https://user-images.githubusercontent.com/171033/182549668-c0db6209-0a07-4478-9593-56ae4d1c82fb.png)

Do you have something overthere in the far riht?

**Comment by yoyurec** [comment]
> somehow it was not in the default set 

you need to install & configure (1 line) "Block calendar" - it's collab ))

**Comment by emms007** [comment]
I have good result to limit the number of lines with an elipse, while keeping a font resizing that changes if the window is full or semi.

Semi sized window:
![image](https://user-images.githubusercontent.com/171033/182612958-8f060086-6991-4ba9-a534-ade69b6afd50.png)

Full screen window (text is fit, and further text is displayed)
![image](https://user-images.githubusercontent.com/171033/182613396-4ffb9f75-7e6c-407a-b9fd-4e0aca65bad5.png)



```
<div id="banner-widgets-quote">
<div id="banner-widgets-quote-child">
<p>This is the true joy in life:
being used for a purpose recognized by yourself as a mighty one;
being a force of nature instead of a feverish, selfish little clod of ailments and grievances complaining that the world will not devote itself to making you happy.
I am of the opinion that my life belongs to the whole community, and as long as I live it is my privilege to do for it whatever I can. I want to be thoroughly used up when I die, for the harder I work the more I live.
I rejoice in life for its own sake. Life is no "brief candle" for me. It is a sort of splendid torch which I have got hold of for the moment, and I want to make it burn as brightly as possible before handing it on to future generations.</p>
</div>
</div>
```


![image](https://user-images.githubusercontent.com/171033/182612754-236583a7-0a44-4428-abcf-b96ff9083445.png)

```
div#banner-widgets-quote {
    position: absolute;
    top: 40%;
    right: 20px;
    background-color: rgba(var(--widgetsBgColor), 0.3);
    backdrop-filter: blur(1px);
    filter: saturate(0.8) drop-shadow(0px 1px 0px black);
    width: 30vw;
    padding: 10px;
}

div#banner-widgets-quote-child {
    text-shadow: 0px 0px 6px white, 0px 0px 3px white;
    font-size: calc(0.45em + 1vmin);
    text-overflow: ellipsis;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 5;
    -webkit-box-orient: vertical;
}
```

**Comment by yoyurec** [comment]
line clamping good idea, but as this is a plugin - I can use JS to set font size, according to quote length!

**Comment by yoyurec** [comment]
looks like I've found a nice visual style
![image](https://user-images.githubusercontent.com/137919/182689625-60a1fe6b-f5a4-4dd3-80f4-0d9f1abe2bef.png)

**Comment by yoyurec** [comment]
Try new release **v3**

**Comment by emms007** [comment]
Result is awesome on your screen shots 💯  Love it. !

I can't quite reproduce the same yet, it seems I get some bugs:

1. bgcolor is weirdly defined, I am not sure where this is set it seems it it managed by the code, not configuration?
![image](https://user-images.githubusercontent.com/171033/182812338-a086e995-b1d4-4871-a4ea-38b8d6142937.png)

2. Somehow the weather lost its form from the former release 
![image](https://user-images.githubusercontent.com/171033/182812507-97f5c001-0d11-49c0-bf35-6b32a19b6963.png)

3. When clicking on journal to get others quotes, sometimes it retrieve a block that is not tagged with #Quote - at all  .. I am not sure see to get why. Can you reproduce this?

4. In the cleansing of the quote, it should probably remove properties. I assume one would not really put properties  in quote, but if you make a reference to it, it gets an ID property:
![image](https://user-images.githubusercontent.com/171033/182812899-ccff9d54-602e-483d-8c93-afd75c13c875.png)

**Comment by yoyurec** [comment]
what theme are you using?

**Comment by yoyurec** [comment]
weather now horizontal

**Comment by yoyurec** [comment]
3. ... in addition plugin sesrch for `> I'm Logseq standard quote too`  texts

**Comment by yoyurec** [comment]
4. will check. don't use references, so wasn't able to see bug

**Comment by emms007** [comment]
1. **Background color**
- I use theme logseq-bonofix-theme. But I see "widgetsBgColor" only mentionned in the banner plugin. Do you expect this to be set by the theme?
- Yes I use the latest
- I tried to set a custom value to widgetsBgColor but as it it set at 255,NA,NA somewhere I can't override it (unless I add !important)

2. **Weather**
- Ok I just figured out it is not horizontal. In my case it is not fully aligned on the left side (due to left: -162px).
Maybe you can replicate with https://indify.co/widgets/live/weather/GmOMONZ9ld2zMLG8wP4a
![image](https://user-images.githubusercontent.com/171033/182822696-5f78098f-7c80-4fe9-9a68-d827a8383927.png)

3.**Quote are #Tag + ">"**: could we have this as an option? ">" is a style  I use, but I would say I don't use this for "high quality quote" I want to see on the banner :)

**Comment by yoyurec** [comment]
1. Background color
it's generated (t ohave possibility add opacity) by JS from default Logseq vars.
if they are not in HEX - you'll have a problem.
ask your developer theme to add Banners support... or set them by yourself (`--ls-primary-text-color` & `--ls-primary-background-color`)
2. weather SHOULD NOT be aligned on left:0 - it became too long. nobody needs city name ))
have you changed width/height? DON NOT DO this. it's pixel perfect adjusted "out of the box" with plugin CSS
3. em... makes sense to delete it from search results and leave only tag (BTW, it's hardcoded)

**Comment by yoyurec** [comment]
3. release updated

**Comment by emms007** [comment]
1. 
I have color set in my theme, but I see that the JS conversion won't work because "--ls-primary-background-color: #fff" is not properly parsed by hexToRGB.  Not sure if you want to address it or we assume my initial value isn't per the strict standards.

2. I get your point about hiding the city. In my case the value won't work with left -167. I'll adapt manually with. Could we that our city names are differents ? I did not play with the sizes from out of the box settings.
```
#banner-widgets-weather {
    left: -127px;
    -webkit-transform-origin-x: 0;
}
```

**Comment by emms007** [comment]
Edit: in dark theme, my background color is rgb(47, 52, 55) from the theme. hexToRBG does not like it neither.

**Comment by emms007** [comment]
the below works fine from https://stackoverflow.com/a/13714351/3329985

```
var canvas = document.createElement("canvas");
var ctx = this.canvas.getContext('2d');

ctx.fillStyle = "rgb(pass,some,value)";
var temp =  ctx.fillStyle;
ctx.fillStyle = "rgb(47, 52, 55)"
```
=> ctx.fillStyle

```
var canvas = document.createElement("canvas");
var ctx = this.canvas.getContext('2d');

ctx.fillStyle = "rgb(pass,some,value)";
var temp =  ctx.fillStyle;
ctx.fillStyle = "#fff"
```
=> ctx.fillStyle

**Comment by yoyurec** [comment]
There are TONS  of color spaces variations (don't forget about Alpha chanel)...
I can't fight (**=**detect+convert) all of them - https://css-tricks.com/converting-color-spaces-in-javascript/
Default Logseq + few top themes works fine.
Other themes devs (or users via PR) can change without pain just 2 colors, IMHO. it's not changing the value, just format.

As for me - i will add ugly, non transparent fallback of course, thx for issue report!

**Comment by emms007** [comment]
Yes there are plenty, but the lead given in https://github.com/yoyurec/logseq-banners-plugin/issues/41#issuecomment-1205130647 will cover whatever source to a valid Hex you can parse, isn't it?

**Comment by yoyurec** [comment]
will check tnx

meanwhile - update to latest:
* 3digit hex added (back 😊, it was sometime ago...) - so Bonofix theme works
* weather width settings added - so adjust it so you city is hidden (= 690px)

**Comment by emms007** [comment]
All is good ! So happy to see my quote-all-of-fame with me all the time! So inspiring.

The WIDTH aspect of the weather was good but I noticed that it won't help so easily as the object in the weather iframe position are changing as the weather condition are changing "sun=3 letters, thunderstrom=way more text, and blocks are at very different spaces"

I eventually went with the below override, and reducing the scale further (I am not sure it is fully required). You'll see over the next days on your side too, as your local weather change :):

```
#banner-widgets-weather {
    left: 0;
    width: 0px
    transform: scale(0.7) translate(-55%);
}
```

Thanks a lot

**Comment by yoyurec** [comment]
maybe need more negative feedbacks (have no idea of weather % usage) to movi it back to vertical variation )))
but i so want to fit it compact with calendar 😒

**Comment by yoyurec** [comment]
as injecting CSS into iframe is forbidden due to CORS (in opposite as i did for Tabs plugin) - need to try proxy. Fetch widget and parse iframe, rework source and throw resulted HTML....

**Comment by yoyurec** [comment]
> 

nice solution, BTW. found variation with RGBA, so no need HEXtoRGB();
``
  const canvas = document.createElement('canvas');
  canvas.height = 1;
  canvas.width = 1;
  const context = canvas.getContext('2d');
  context!.fillStyle = color;
  context!.fillRect(0, 0, 1, 1);
  const rgbaArray = context!.getImageData(0, 0, 1, 1).data;
```
