### ISSUE TITLE
[Feature Request] Toggle Widgets

### ISSUE THREAD

**Issue by jacobtfisher** [yoyurec/logseq-banners-plugin#42]
Hey there - thanks for making a really nice Logseq plugin. I like the updates in the latest version, but it would be nice to easily turn off the widgets since it's not a feature that I use. I figured out that I can edit the links to the widgets to remove them, but a toggle would be nicer so I can turn them off entirely. Thank you!

**Comment by jacobtfisher** [comment]
Hmm. In that case, it might be a good idea to separate the widget functionality into its own plugin (kind of like how the calendar you can put in the banner is a separate widget). This would let you keep the banner plugin simple for the people like me who just want banners and custom page icon options and then have a separate banner widgets plugin that could have more options without cluttering the main banners plugin. 

Anyway, you can feel free to close since I was able to find a solution, but might be something to think about for the future. Thanks again for making the plugin!

**Comment by yoyurec** [comment]
BTW, you can use `custom.css` as **toggler**
```css
#banner-widgets {display: none !important;}
```

**Comment by yoyurec** [comment]
> separate banner widgets plugin
i tried, but they are to connected and reuse a lof of logic ((

> This would let you keep the banner plugin simple for the people like me who just want banners
oh... makes sence. le'ts do this! )

**Comment by yoyurec** [comment]
check latest ver

**Comment by jacobtfisher** [comment]
Awesome! Thank you! I really appreciate the effort. I'll close this issue for now since my concern is addressed.

**Comment by yoyurec** [comment]
Check even more settings in new release **v3**! 😎
