### ISSUE TITLE
Banner didn't show while using a local relative path

### ISSUE THREAD

**Issue by Brainattccker** [yoyurec/logseq-banners-plugin#43]
I use the lastest windows10. The path was correct, but banner didn't show up. I've tried many times,  but resulted in no differences.
![image](https://user-images.githubusercontent.com/53453045/182790489-efcbe38c-f542-448f-8ae3-3fc33e590b88.png)
However, with a absolute path, it works fine.
![image](https://user-images.githubusercontent.com/53453045/182791316-577aa765-9366-40c5-8735-5aa60fb55153.png)

**Comment by yoyurec** [comment]
use proper slashes!
how to do this? add image in Logseq note and just copy it's path 🎉

![image](https://user-images.githubusercontent.com/137919/182792808-5bf78bdb-bbc5-49a9-b03f-2a58b246ff95.png)

**Comment by Brainattccker** [comment]
> use proper slashes! how to do this? add image in Logseq note and just copy it's path 🎉
> 
> ![image](https://user-images.githubusercontent.com/137919/182792808-5bf78bdb-bbc5-49a9-b03f-2a58b246ff95.png)

I just followed what you said, but still nothing happened......

**Comment by Brainattccker** [comment]
Ouch!It seems that i didn't have the latest plugin....I updated just now, and everything is solved.....I today downloaded it from the official market, didn't expect it to be a old version. Sorry for my mistake! Problem solved

**Comment by yoyurec** [comment]
hm... local assets support was here long time ago... strange
maybe page props were heavy cached by Logseq, dunno ((
