### ISSUE TITLE
Weather app alignment

### ISSUE THREAD

**Issue by gammonmark** [yoyurec/logseq-banners-plugin#45]
Just upgraded to v. 3.04. Once I got the weather widget re-added, I'm noticing a slight alignment issue where the left edge of the widget shows what I believe is a part of the lettering for my selected city. Maybe I can tweak this in CSS someplace? Or it can be fixed in the plugin..

![CleanShot 2022-08-04 at 08 50 59](https://user-images.githubusercontent.com/5113951/182879241-6a1d165c-cedd-40fd-a071-7046ebce3037.png)

**Comment by yoyurec** [comment]
update to 3.0.6 and adjust (newly added) "weather widget width" value in settings, so your city become hidden on left

**Comment by gammonmark** [comment]
Got it and worked to help hide the city. Thanks Yurii
