### ISSUE TITLE
Calendar / weather not transparent

### ISSUE THREAD

**Issue by ituri** [yoyurec/logseq-banners-plugin#46]
I followed the instructions for setting up the calendar and the weather widget, however it does not appear to be transparent. Is there anything I can do to fix this
![Screenshot 2022-08-05 at 12 53 45](https://user-images.githubusercontent.com/871297/183063193-5f5c879c-ed52-4114-a186-b81e8d6f8eb4.png)
?

**Comment by yoyurec** [comment]
it's transparent, but dark. check your custom.css or theme - plugin reuses main bg color `--ls-primary-background-color`

**Comment by yoyurec** [comment]
fixed in v3.1.3

**Comment by ituri** [comment]
Thank you!
