### ISSUE TITLE
Square content before Quote

### ISSUE THREAD

**Issue by cliffordx** [yoyurec/logseq-banners-plugin#47]
I don't know if I'm only one having this but how to remove this square before the Quote?
<img width="999" alt="Screen Shot 2022-08-06 at 1 29 08 PM" src="https://user-images.githubusercontent.com/7141739/183235602-1507bf0b-e642-4366-bece-71d9c68545f2.png">

**Comment by yoyurec** [comment]
check new update **v3.0.7**
