### ISSUE TITLE
How to remove the banner accidentally added by the plugin in other pages?

### ISSUE THREAD

**Issue by DelmarHuang** [yoyurec/logseq-banners-plugin#48]
After installing it, every page will add a banner but I only want to add it in journals so I canceled the setting. But I cannot remove those ones which already had automatically. How should I do it? Thank you!

**Comment by yoyurec** [comment]
have you deleted the banner URL?
![image](https://user-images.githubusercontent.com/137919/183411270-45e9c751-5912-47c9-a4b2-74982fc3d88a.png)

**Comment by DelmarHuang** [comment]
Done! Thank you!
