### ISSUE TITLE
Feature Request: change quote font size

### ISSUE THREAD

**Issue by ms3056** [yoyurec/logseq-banners-plugin#49]
I'd like to change the font size if the quote widget.

**Comment by emms007** [comment]
@ms3056 

This is Simple CSS you can put in logseq config > edit custom.css

for instance:
`div#banner-widgets-quote-text {
    font-size: 80%;
    line-height: 130%;
}`

**Comment by yoyurec** [comment]
#banner-widgets-quote-block size dynamically calculates in JS according to quote length,
so you can use child #banner-widgets-quote-text to set % value as described before

@ms3056 BTW, you want it smaller or bigger? just interesting as UI/UX aspect...

**Comment by ms3056** [comment]
> #banner-widgets-quote-block size dynamically calculates in JS according to quote length, so you can use child #banner-widgets-quote-text to set % value as described before
> 
> @ms3056 BTW, you want it smaller or bigger? just interesting as UI/UX aspect...

Hi! I would like to make it smaller - which your custom CSS hint achieved perfectly - thank you!

**Comment by yoyurec** [comment]
feature added in https://github.com/yoyurec/logseq-banners-plugin/releases/tag/v3.3.0

**Comment by ms3056** [comment]
HI - my quotes are no longer working. I uninstalled the plugin, reinstalled it and restarted Logseq:

![image](https://user-images.githubusercontent.com/23712700/184732433-53324f2a-1965-4265-915a-1ce9d6135e64.png)

**Comment by yoyurec** [comment]
any details?
can you post quotes md example?

**Comment by ms3056** [comment]
[Quotes.md](https://github.com/yoyurec/logseq-banners-plugin/files/9340327/Quotes.md)

Attached. I didn't make any changes to this file since the update. 


![image](https://user-images.githubusercontent.com/23712700/184733641-c595d786-8f02-4234-a16c-6f675810f82b.png)

**Comment by yoyurec** [comment]
oh, i'v found )) 
bug with unreverted static code from experiments
update to latest!

**Comment by ms3056** [comment]
> 

Happy to have helped! Thank you for the time you put into this!!
