### ISSUE TITLE
Quote: have a way to have a regex to clean the text

### ISSUE THREAD

**Issue by emms007** [yoyurec/logseq-banners-plugin#50]
Hi 
I am wondering if it would make sens to have a configuration text input that would allow to type down a regex to clean the quote.
For instance, I'd be happy to set-in that:
- anything that is id:: XX-ZZ-SS has to be cleaned
- similar for SCHEDULED: <..>$
- similar for ^TODO
- remove any tag reference at the beginning, or, at the end of the quote
- clean any "^" in the usual usage of "^^text^^"  because anyhow this is not rendered by the quote

**Comment by yoyurec** [comment]
yes, now it's done for easy texts (only tag deleted and italic (`**text**`) supported.

thx for input, will all clean up later (hardcoded... not sure it can be nice possibility to confire - at least Logseq settings have no `texarea` field 😥)

**Comment by emms007** [comment]
FYI the logseq-habit-tracker plugin allows regex input as part of its configuration.
That is not a "textarea" but that fit quiet well for regex.
Having an initial proposal with the default setting for the average use is good, then for others, up to them to adapt.

![image](https://user-images.githubusercontent.com/171033/184352952-2b7ba978-7060-4cb0-855d-8d1a7239b050.png)

**Comment by yoyurec** [comment]
> similar for SCHEDULED: <..>$
> similar for ^TODO

who will "todos" and schedule quotes??? ))

**Comment by emms007** [comment]
Thats why a regex would be nice.. we probably dont have the same relationship with quotes ;)
Why would anyone do this? Because you want to "acknowledge" the quote every month for instance. Making sure you don't loose track of your ambitions ;)

**Comment by yoyurec** [comment]
feature added in https://github.com/yoyurec/logseq-banners-plugin/releases/tag/v3.2.0
