### ISSUE TITLE
Quote: go back to origin

### ISSUE THREAD

**Issue by emms007** [yoyurec/logseq-banners-plugin#51]
I am dreaming that the quote Icon that I see on the top-left of the block would be able to have me reach the page & block where that quote was located?

Use case would be:
1. I see a great quote
2. I want to jump back in the original page/context where it was taken

Currently I use the search function to type back parts of the quote and locate it. This could be saved.

**Comment by yoyurec** [comment]
thinking about same few days ))
need to write proper db query for this, investigating...

**Comment by yoyurec** [comment]
feature added in https://github.com/yoyurec/logseq-banners-plugin/releases/tag/v3.2.0
