### ISSUE TITLE
Block calendar data Show twice

### ISSUE THREAD

**Issue by unix2dos** [yoyurec/logseq-banners-plugin#52]
![iShot_2022-08-15_14 34 30](https://user-images.githubusercontent.com/22365670/184587699-07aeffed-a5c0-44b9-a2b1-583da9d81b05.jpg)

**Comment by yoyurec** [comment]
Banners plugin do no do rendering of calendar.
Go to original plugin issues https://github.com/vipzhicheng/logseq-plugin-block-calendar/issues
