### ISSUE TITLE
Custom Pomodoro Notifications

### ISSUE THREAD

**Issue by xf-zhao** [yoyurec/logseq-banners-plugin#56]
Hi, thank you for this wonderful work! I really like this plugin.

I tried the Pomodoro feature but found that it will alert 5min before the actual ending, which is actually a distraction to me. I didn't find any options on the setting page. Can it be customized so the user can turn off the early alert feature?

Thank you!

**Comment by yoyurec** [comment]
pomodoro - is not a feature!
it's a demo for custom html (= using iframes)!
find your pomodoro widget and replace current
or use pomodoro plugins
![image](https://user-images.githubusercontent.com/137919/189528071-994a9382-f451-46bd-9d0f-1f382d48259c.png)

or use pomodoro feature from Agenda plugin
![image](https://user-images.githubusercontent.com/137919/189528087-2f451453-ca1f-441f-926f-6f3237888d25.png)
