### ISSUE TITLE
Block Calendar is dark in Banner

### ISSUE THREAD

**Issue by gammonmark** [yoyurec/logseq-banners-plugin#57]
With the Logseq update to 8.7 I've run into a strange issue with the rendering of the Block calendar in the banner on Journal pages. This screenshot is from the Solarized theme, but the issue remains regardless of the chosen theme, I tested on the Github and Logseq default light themes. I don't believe I can adjust this via any settings among the theme or other plugins?

![CleanShot 2022-09-14 at 13 49 36](https://user-images.githubusercontent.com/5113951/190249561-e97b9b55-3640-42af-ad54-59649c2dd647.jpg)

**Comment by yoyurec** [comment]
i've seen the same, but after reload issue have gone. do you still see it?

**Comment by gammonmark** [comment]
I have reloaded and restarted multiple times but still have the issue. I'll keep trying some things.

**Comment by gammonmark** [comment]
Reload did not resolve. But toggling the plugin off, then reloading, and toggling the plugin back on has done it for me. Thanks, hope this might help if any others have issue.

**Comment by gammonmark** [comment]
Actually, each time I shut down and restart Logseq this is occurring and does not always resolve with toggling. Sometimes it is a light color over the block calendar (no dates) or dark like previous screenshot. 
![CleanShot 2022-09-15 at 14 45 51](https://user-images.githubusercontent.com/5113951/190505493-76ef9f48-a712-4b74-bcf7-19343ac06481.jpg)

**Comment by yoyurec** [comment]
ok, will recheck

**Comment by yoyurec** [comment]
fixed, check latest release **v3.4.3**

**Comment by gammonmark** [comment]
Awesome, looks good. Thanks!

**Comment by Joseph-zheng** [comment]
Actually, each time I shut down and restart Logseq this is occurring and does not always resolve with toggling. Sometimes it is a light color over the block calendar (no dates) or dark like previous screenshot.

same problem

**Comment by gammonmark** [comment]
This is occurring for me again too. This is after the latest update to 3.4.8
![CleanShot 2023-01-20 at 07 59 00](https://user-images.githubusercontent.com/5113951/213730028-e0d50b97-3034-44d2-9086-928f2bd47a4c.jpg)

**Comment by sawhney17** [comment]
Investigating...

**Comment by Joseph-zheng** [comment]
> This is occurring for me again too. This is after the latest update to 3.4.8 ![CleanShot 2023-01-20 at 07 59 00](https://user-images.githubusercontent.com/5113951/213730028-e0d50b97-3034-44d2-9086-928f2bd47a4c.jpg)

same to me for the latests version, and the quote seems ……（#quote）
![image](https://user-images.githubusercontent.com/18510737/213848102-ba0f5fe6-17b5-48be-8c1a-1cd9f53ec169.png)
