### ISSUE TITLE
Quote content handling

### ISSUE THREAD

**Issue by sethyuan** [yoyurec/logseq-banners-plugin#58]
I'm having problems using the quotes, you can see some of them in the screenshots.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/3410293/192677878-2da451b7-8f27-4a24-aa80-ae478e1124ba.png">

<img width="493" alt="image" src="https://user-images.githubusercontent.com/3410293/192677944-e07f96ca-9911-4747-a6d2-d1c43e2a89a8.png">

Content handling can be improved. I have a piece of code that handles this kind of cases that I used in TOC Generator, maybe you can take a look of it and make some adjustments?

https://github.com/sethyuan/logseq-plugin-tocgen/blob/33c73eadf33034bce8a264c37ba6107cbb39554f/src/utils.js#L3

This is great plugin by the way.

**Comment by yoyurec** [comment]
hi! tnx for inputs, will check later

**Comment by yoyurec** [comment]
fixed, check latest release
