### ISSUE TITLE
Weird spacing in "Favourites" and "Recent"

### ISSUE THREAD

**Issue by candideu** [yoyurec/logseq-banners-plugin#59]
I really like this plugin! Unfortunately, I get this weird spacing on the left panel for pages listed in "Favourites" and "Recent":

![image](https://user-images.githubusercontent.com/55474996/193136847-4b1432c5-6626-4c37-99b9-d944ef869c77.png)

I've turned off all other plugins and themes, and it appears that this plugin is the culprit.

**Comment by yoyurec** [comment]
which theme are you using?
do you have same on default theme?

**Comment by dmytrodubinin** [comment]
The same problem only in Logseq 0.8.8 (default and custom themes, after reindex)

**Comment by yoyurec** [comment]
check latest release!

**Comment by candideu** [comment]
I’ve set it to the default theme, and it still happens.

On the “Journal” page, it’s fine, but once I click on a page, the glitch happens.

**Comment by yoyurec** [comment]
not sure you are using latest plugins. all other ppl have no isse anymore

**Comment by candideu** [comment]
> @candideu not sure you are using latest plugins. all other ppl have no isse anymore

That was a reply I sent ages ago, not sure why it only posted recently. Please disregard.

I updated the plugin 10 days ago when you sent the message here.

> looks like Logseq 0.8.8 changed markup ((
> 
> fixed, check latest release!
