### ISSUE TITLE
Banner image disappear after switch back to Journals 

### ISSUE THREAD

**Issue by jtcpwang** [yoyurec/logseq-banners-plugin#60]
Thanks for providing such an amazing Logseq plugin. Here is one issue when I use local image as banner. 

Steps for reproducing issue:

1. Changed banner settings : defaultJournalBanner to local image, such as "../assets/RE1YtHA_1920x1080_1664862077824_0.jpg" 
, after close setting popup windows,  banner works well. 

2. Click "Journal" menu item, the banner image disappear. 

Could you help to check this issue? Thanks a lot. 

Jt.wang

**Comment by yoyurec** [comment]
fixed, check latest release
