### ISSUE TITLE
Quote is showing tag marks

### ISSUE THREAD

**Issue by compadrejunior** [yoyurec/logseq-banners-plugin#68]
Hi, folks. 

Since version 3.4.8, my banner is show the tags marks in quotes. The problem is even worse when the quote is inside a #BEGIN_QUOTE #END_QUOTE mark. 

Here's an example:

![image](https://user-images.githubusercontent.com/13987735/214378614-d61f491d-75f2-42f8-9260-8cb80862d7b6.png)

How do I solve this?

Thanks in advance. 

Best regards.

José Compadre Junior

**Comment by sawhney17** [comment]
For the quotes, make sure you change the regex from the current to this. `(^(TODO|NOW))|([a-z-]+::[^]*)|(SCHEDULED:.<.*>)|([[)|(]])|(#[w-_+]+)`


You can do so from settings.


Alternatively, you can rebuild the regex through the command palette `Rebuild Regex for Banner Plugin`

**Comment by sawhney17** [comment]
Command pallete is accessible through command shift p

**Comment by compadrejunior** [comment]
Hello, @sawhney17 

Thanks for your reply. 

I tried with the given regex but it generates the following console error:

`banners.ts:839 Uncaught (in promise) SyntaxError: Invalid regular expression: /(^(TODO|NOW))|([a-z-]+::[^]*)|(SCHEDULED:.<.*>)|([[)|(]])|(#[w-_+]+)/: Range out of order in character class (at banners.ts:839:25)
    at new RegExp (<anonymous>)
    at jr (banners.ts:839:25)
    at async kr (banners.ts:786:17)`

Alternatively I've tried the following regex and **it works fine**. 

`(^(TODO|NOW))|([a-z-]+::[^]*)|(SCHEDULED:.<.*>)|([[)|(]])|(\#quote)|(\#\+BEGIN_QUOTE)|(\#\+END_QUOTE)`

Best regards,

José Compadre Junior
