### ISSUE TITLE
block calendar disappear

### ISSUE THREAD

**Issue by cnut1648** [yoyurec/logseq-banners-plugin#69]
Hello, thank you for making such an awesome plugin!

I have a question regarding block calendar integration. I have installed the block calendar following your instruction on Readme. And it was working great. But lately somehow the block calendar just disappeared, as shown in the screenshot
![image](https://user-images.githubusercontent.com/37067883/215345064-dc00dfc7-aa3f-41f8-9f91-a08c6d97c33b.png)

It was working fine so I am not sure what might be the issue is. 
My config for banner (this plugin) is 
![image](https://user-images.githubusercontent.com/37067883/215345109-c620ef44-f570-47ac-b077-bc9e863269cf.png)

while my config for block calendar is 
![image](https://user-images.githubusercontent.com/37067883/215345128-f2db5545-5500-4dfe-961f-3fc14e5dae01.png)
My logseq version is 0.8.16, and I am using latest version of both plugins, namely 0.1.14 for block calendar and 3.4.8 for banner.

I wonder if there are some ways to debug. Thank you!

**Comment by stdword** [comment]
Hello, @cnut1648! There are some updates on block calendar I've made these days. Do you have such problem for block-calendar v0.2.1?

**Comment by cnut1648** [comment]
Thanks @stdword , it seems to work in the latest version!
