### ISSUE TITLE
improvement on quote

### ISSUE THREAD

**Issue by feigaoxyz** [yoyurec/logseq-banners-plugin#73]
currently quote function shows raw text, which does not render any markdown styles. e.g. the sample text `brown **fox** jump [over](http://example.com)` will show as it is.

Suggest to improve the presentation by either 1) render the styles, e.g. "brown **fox** jump [over](http://example.com)"
or 2) remove the markups, e.g. "brown fox jump over"

**Comment by yoyurec** [comment]
fiexed
